// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiaujxnexbsjntlzhorf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pYXVqeG5leGJzam50bHpob3JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzIxMDUsImV4cCI6MjA2MzE0ODEwNX0.GeSB12atRhqEuRD3y5s4Umn4MZ-jRF68AvqU3A8x674";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);